noun = raw_input("Enter a noun ") 
verb = raw_input("Enter a verb ")
adjective = raw_input("Enter an adjective ")
adverb = raw_input("Enter an adverb ")
print("Do you %(verb)s your %(adjective)s %(noun)s %(adverb)s. Thats incredible." % locals())
